org: jritchie1
app: terraformer-tracker
service: terraformer-tracker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  main:
    handler: src/handlers/main.handler
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    TestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TestTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH