org: jritchie1
app: terraformer-tracker
service: terraformer-tracker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:us-east-1:529952220313:table/TestTable

functions:
  main:
    handler: src/handlers/main.handler
    events:
      - httpApi:
          path: /
          method: get
  addExpansion:
    handler: src/handlers/add.expansion
    events:
      - httpApi:
          path: /addExpansion
          method: post
  getExpansion:
    handler: src/handlers/get.expansion
    events:
      - httpApi:
          path: /getExpansion
          method: get

package:
  patterns:
    - '!node_modules/**'

resources:
  Resources:
    TestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TestTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH